### PR TITLE
Error in mounted hook: "TypeError: Cannot read property 'offsetHeight' of null"

### PR DESCRIPTION
**Pull request by simon300000**
if there is a scrollactive-item that have a href does not exist in the page, the mounting process will throw an error "TypeError: Cannot read property 'offsetHeight' of null"

Which is right because the target does not exist, but this should not kill the mounting process, instead, it should output a warning to console.
However, there seems have no problem with the code, because a simple rebuild resolves this issue.

### CODE REVIEW

**Comment by stephanedemotte** [comment]
merge ?

**Comment by Triloworld** [comment]
Pleas, no warning as link with # can be on other page.
For example this error occur on 404 page os SPA and when I click on link, it might go to desired page and scroll to section, not give some error as this type of action is desired. 
Related to this type of scenario: https://github.com/eddiemf/vue-scrollactive/issues/26
And for AJAX adding section when on start isn't there.

**Comment by eddiemf** [comment]
I'm closing this since it's not relevant for a long time as several releases have gone through and now I'm finally with time to maintain and clean my libraries, thanks for the help though :)

**Comment by eddiemf** [comment]
@Triloworld Can you open an issue and explain the situation better, please? I can't really understand what is the problem, I'll be happy to help :)

**Comment by simon300000** [comment]
Yes I believe it is same issue as #26
For some reason it is fixed by rebuilding...

I am happy to hear you had fixed it and thank you.

**Comment by eddiemf** [comment]
Well, I've made some tests adding a scrollactive item referring to an element that doesn't exist and it seems to work as intended, nothing breaking, only thing is that when you click the item it will log a message saying that the item was not found. Thanks for the explanation! If anything just open a new issue and I'll take a look at it :)

**Comment by Triloworld** [comment]
Thanks. It is what we need, no error, only message. if something occur new, then we will create another issue.

**Comment by martijnvanloon** [comment]
I had this issue. It was solved by upgrading to version 0.8.0!

**Pull request closed without merging**
